Issue 38
dotkernel/dot-controller pull request #39
Opened 2024-04-03 15:40 UTC by cPintiuta

2024-04-04 05:49 UTC, alexmerlin requested changes
- also add SECURITY.md file - example [here](https://github.com/dotkernel/dot-annotated-services/blob/5.0/SECURITY.md) - don't forget to adapt it to your package
- do you plan to add more files under `events` and `plugins` directories? if no, move their contents up one level

2024-04-04 05:49 UTC, alexmerlin commented on mkdocs.yml
Replace all `v5` occurences with `v3`.

2024-04-04 05:52 UTC, alexmerlin commented on mkdocs.yml
> +repo_url: "https://github.com/dotkernel/dot-controller"
```suggestion
repo_url: "https://github.com/dotkernel/dot-controller"
plugins:
  - search
```

2024-04-04 12:32 UTC, alexmerlin requested changes

2024-04-04 12:32 UTC, alexmerlin commented on composer.json
> +            "laminas/laminas-dependency-plugin": true
```suggestion
            "laminas/laminas-dependency-plugin": false
```

2024-04-05 08:51 UTC, alexmerlin approved these changes

2024-04-05 09:08 UTC, arhimede approved these changes

2024-04-05 09:08 UTC, merged